server:
  port: 8010  # Ensure it’s not using the same port as Auth Service

spring:
  application:
    name: USER-SERVICE  # Unique service name

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30  # Sends heartbeats every 30 sec
    lease-expiration-duration-in-seconds: 90    # Expiry time for removing dead instances
