server:
  port: 8000  # Ensure it’s not using the same port as Auth Service

spring:
  application:
    name: AUTH-SERVICE  # Ensure this is unique

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 15  # Heartbeat interval
    lease-expiration-duration-in-seconds: 90  # Expiry time for removing dead instances
