server:
  port: 8090  # API Gateway runs on this port

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth-service/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5  # Increased since auth calls may need more requests
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@rateLimiterKeyResolver}"


        - id: club-service
          uri: lb://CLUB-SERVICE
          predicates:
            - Path=/api/club-management/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 4  # Clubs might have frequent interactions
                redis-rate-limiter.burstCapacity: 8
                key-resolver: "#{@rateLimiterKeyResolver}"

        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/events/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2  # Events may not need frequent calls
                redis-rate-limiter.burstCapacity: 5
                key-resolver: "#{@rateLimiterKeyResolver}"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: KWYhl/YNG4smxQfnh+D/868qiQV4bHgKzQSezvS3gNQ=
