server:
  port: 8090  # API Gateway runs on this port

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth-service/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user-management/**

        - id: club-service
          uri: lb://CLUB-SERVICE
          predicates:
            - Path=/api/club-management-service/**

        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/events/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: KWYhl/YNG4smxQfnh+D/868qiQV4bHgKzQSezvS3gNQ=
